### ISSUE TITLE
PhpStorm 2022.2.1 RC issue

### ISSUE THREAD

**Issue by pnlinh** [brendt/phpstorm-light-lite-theme#4]
Hi @brendt,

I really like the theme you have created and would love to use it. However, with this new PhpStorm 2022.2.1 RC, it doesn't seem as pretty as the old version. Do you have any updates? Thanks

- Phpstorm 2022.2.1 RC version:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/26193890/184799176-7f0c0123-a85f-4779-8f48-244d68f32b6c.png">

- Phpstorm 2022.2:
![image](https://user-images.githubusercontent.com/26193890/184799434-ad380dba-00a0-4896-a215-b8f56b47bdf8.png)

**Comment by brendt** [comment]
Could this be a font issue?

**Comment by pnlinh** [comment]
@brendt  yes, I think so. Hope you have an update on this issue.

**Comment by brendt** [comment]
You should probably choose another font or play around with anti alias settings, I don't have any issues myself, sorry
