### ISSUE TITLE
Array color highlight?

### ISSUE THREAD

**Issue by devheniik** [brendt/phpstorm-light-lite-theme#5]
The screenshot shows that the array key matches its style with the parent key and also matches the value that is assigned to it

Do you have any ideas on how to diversify it so that everyone likes it? Perhaps you would like to create several branches with different styles of this package?

![image](https://user-images.githubusercontent.com/75083421/206726836-7f88da2c-6d41-4ecd-830d-696f8cf0d534.png)

**Comment by brendt** [comment]
I don't intend to maintain several branches :) Feel free to fork and make your own changes :)
